import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './styles/main.css'

import Footer from "./components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        <link rel="preconnect" href="https://images.unsplash.com" crossOrigin="" />
        <link rel="preconnect" href="https://www.fortunefoods.com" crossOrigin="" />
        <link rel="preconnect" href="https://5.imimg.com" crossOrigin="" />
        <link rel="preconnect" href="https://www.patanjaliayurved.net" crossOrigin="" />
        <link rel="preconnect" href="https://www.bigbasket.com" crossOrigin="" />
        <link rel="dns-prefetch" href="https://images.unsplash.com" />
        <link rel="dns-prefetch" href="https://www.fortunefoods.com" />
        <link rel="dns-prefetch" href="https://5.imimg.com" />
        <link rel="dns-prefetch" href="https://www.patanjaliayurved.net" />
        <link rel="dns-prefetch" href="https://www.bigbasket.com" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Footer/>
      </body>
    </html>
  );
}

